### ISSUE TITLE
Fazer uma gitpage

### ISSUE THREAD

**Issue by seraphritt** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#18]
## Descrição
Abrir uma gitpage para documentar o que aconteceu nas reuniões, documentar sobre o projeto, tecnologias utilizadas, instruções de uso, etc.

## Tarefas
Liste as tarefas específicas que precisam ser concluídas para resolver o problema ou concluir a tarefa, dívida tarefas grandes e complexas em tarefas simples.
- [x] Abrir uma gitpage
- [x] Adicionar a ata das duas reuniões passadas

**Comment by GZaranza** [comment]
Subi a gitpages e o @GabrielSPinto ja adicionou os dois docs das duas primeiras reuniões.

Para atualizar a gitpages é so colocar os aquivos na pasta docs e fazer o git pull que ja tem workflow da da o build e deploy da pagina

**Comment by GZaranza** [comment]
Quando tiver modificando a gitpages, principalmente, no mkdocs.yml, para vizualizar como a gitpages ficará basta mudar para a branch "main", dar os comandos "mkdocs gh-deploy" e depois "mkdocs serve" no terminal. Aparecerá o link do serve local rodando a gitpages, qualquer alteração que vc faça nos docs é mudada automaticamente no serve sem precisar dar os comandos de novo, caso modifique algo no mkdocs.yml, precisará fechar o serve(crtl + c no terminal) e dar os dois comandos de novo. Quando terminar de fazer as alterações ver no serve local que está tudo certo, é so dar o commit
