### ISSUE TITLE
Estudo sobre o Telebot

### ISSUE THREAD

**Issue by seraphritt** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#19]
## Descrição
Estudar sobre a API do telebot e, se possível, tentar fazer a integração com o telegram.

## Tarefas
Liste as tarefas específicas que precisam ser concluídas para resolver o problema ou concluir a tarefa, dívida tarefas grandes e complexas em tarefas simples.
- [x] Estudar o funcionamento das requisições. 
- [x] Estudar como armazenar as opções selecionadas anteriormente.
- [x] Tentar fazer um bot que integre o script do chatbot com o telegram.
## Testes / Avaliação
Especifique os critérios de teste ou avaliação que serão usados para garantir que a solução seja eficaz. 
- [x] Testar o bot e verificar se o fluxo está sendo seguido

**Comment by GZaranza** [comment]
Documentação da lib telebot https://pytba.readthedocs.io/en/latest/index.html

**Comment by Gxaite** [comment]
Durante o desenvolvimento, utilizamos a biblioteca telebot para criar nossa API. Ao longo desse processo, aprofundamos nosso entendimento sobre as requisições da API, o que nos permitiu implementar uma máquina de estados eficiente para armazenar o estado atual da aplicação. Essa abordagem nos proporcionou uma estrutura sólida e escalável para gerenciar o fluxo de informações e interações dentro da nossa aplicação.
