### ISSUE TITLE
Estudar sobre o Rasa

### ISSUE THREAD

**Issue by seraphritt** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#2]
## Descrição
Configurar um ambiente Python com o Rasa instalado e estudar sobre como utilizar essa ferramenta.

## Tarefas
- [x] Instalar o Rasa utilizando ``pip install rasa``, com o Python na versão 3.10.
- [x] Executar o comando ``rasa init``
- [x] Executar o comando ``rasa train``
- [x] Executar o comando ``rasa shell``
- [x] Conversar com o ChatBot

## Testes / Avaliação
- [x] Verificar se todos as tarefas foram feitas com sucesso

**Comment by GabrielSPinto** [comment]
Pra rodar a API do rasa é necessário o comando
`rasa run --enable-api`

Além disso, é necessário configurar um arquivo de ambiente `.env`. O conteúdo desse arquivo declara a variável de ambiente chamada no arquivo TelegramIntegration.py, deve ser definido:
```TELEGRAM_TOKEN="SEU_TOKEN"```

**Comment by GZaranza** [comment]
Decidimos continuar o projeto usando o Rasa e o bot conectado direto no BP, sem o uso do telegram como intermediador

**Comment by seraphritt** [comment]
Foi decidido utilizar o Botpress em vez do Rasa.
