### ISSUE TITLE
Organização e Planejamento das próximas sprints e releases

### ISSUE THREAD

**Issue by seraphritt** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#21]
## Descrição
Organizar e planejar as próximas sprints, com datas, issues e objetivos bem definidos. 

## Tarefas
- [x] Fazer uma reunião diariamente para pareamento do time (pode ser assíncrono, no whatsapp)
- [x] Fazer uma reunião semanalmente para decidir como será a próxima sprint, sempre baseada no produto final que deverá ser entegue em cada release.

**Comment by seraphritt** [comment]
Podemos usar como exemplo o que o Giovanni fez:
https://giovannialvissus.notion.site/Release-1-1a5639da5ad242118ef4f48d570175b9

**Comment by seraphritt** [comment]
Criamos um grupo no whatsapp onde relatamos diariamente o que estamos fazendo e o que pretendemos fazer no dia.

**Comment by Gxaite** [comment]
Após conversa com o gestor e reunião com os responsáveis pelo Brasil Participativo tivemos uma noção boa do que era esperado do produto e podemos delimitar melhor nossas sprints e entregas durante o projeto Brisa.
