### ISSUE TITLE
Pesquisar alternativas de integração pelo intergram

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#26]
## Descrição
Estamos com problemas para integrar o nosso bot no site do Brasil participativo, a alternativa usado pela aplicação é inviavél pelas limitações do Telegram

## Tarefas
- [x] Procurar alternativas de solução a curto prazo para o problema do intergram
- [x] Avaliar a possibilidade de usar webhook
- [x] Avaliar a possibildiade de criar um script para reenviar a mensagem pro nosso bot

## Testes / Avaliação
- [x] Testar se o bot funcionaria com várias pessoas
- [x] Testar possivéis limitações quanto a API do Telegram

**Comment by seraphritt** [comment]
Devido à inviabilidade do telegram, decidimos por não usar o integram e em alternativa usaremos o Rasa com o webchat (widget).
Página da documentação do widget: https://chat-widget-docs.rasa.com/
