### ISSUE TITLE
Elicitação de Requisitos

### ISSUE THREAD

**Issue by seraphritt** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#33]
## Descrição
Elencar os requisitos do produto (Chatbot) para que possa ser possível ter uma visão mais objetiva do que devemos avaliar no processo de desenvolvimento do produto, bem como as funcionalidades esperadas.

## Tarefas
- [x] Fazer o levantamento de requisitos
- [x] Avaliar se os requisitos condizem com o objetivo final do produto

## Testes
- [x] Validar com o cliente os requisitos

**Comment by Gxaite** [comment]
Antes de adicionarmos os requisitos e histórias de usuários ao GitPage, vamos elaborá-los em um documento compartilhado no Docs.
Segue o link abaixo:
https://docs.google.com/document/d/1-_Q0IOZ91PQHBa_3-IegFL8iciRsi7xsV-mE50P4HY0/edit?usp=sharing

**Comment by seraphritt** [comment]
# *Conclusão*
Foi criado uma seção Backlog do Produto na qual foi adicionada os requisitos não funcionais e funcionais do produto.
A página pode ser acessada pelo link abaixo:
# *Referências*
https://residenciaticbrisa.github.io/T2G2-Chatbot-Participacao-Social/backlog/
