### ISSUE TITLE
Divisão de funções dos membros

### ISSUE THREAD

**Issue by ThiagoMarquesAeroespacial** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#34]
## Descrição
Nesta issue, estamos planejando a divisão de tarefas para o projeto Chatbot Participação Social. Para garantir um desenvolvimento eficiente e organizado, é crucial atribuir responsabilidades específicas a cada membro da equipe.

## Tarefas

- [x] Backend
- [x] Inteligência artificial
- [x] Scrum master
- [x] Documentação
- [x] Frontend

## Testes / Avaliação
- [x] Validar com todos os membros a função de cada um.

## Responsáveis
Todos os membros

## Prazos
21/03/2024

**Comment by Gxaite** [comment]
A divisão do grupo foi decidida e válidada por todos>
Backend - Gabriel Scheidt
Inteligência artificial - Isaque Augusto
Scrum master - Gabriel Zaranza
Documentação - Gabriel Santos
Frontend - Thiago Marques

**Comment by Gxaite** [comment]
A divisão do grupo foi decidida e válidada por todos>
Backend - Gabriel Scheidt
Inteligência artificial - Isaque Augusto
Scrum master - Gabriel Zaranza
Documentação - Gabriel Santos
Frontend - Thiago Marques
