### ISSUE TITLE
Criação de Histórias de usuário

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#36]
## Descrição
É importante criar e incluir histórias do usuário em um documento, além de verificar com o cliente se o que foi desenvolvido atende às necessidades, para termos uma ideia clara do que será necessário para futuras entregas do produto.

## Tarefas
- [x] Criação de histórias de usuários.
- [x] Refinamento dos requisitos a partir dessas histórias.

## Testes / Avaliação
- [x] Validação das histórias com o cliente.

**Comment by Gxaite** [comment]
Antes de adicionarmos os requisitos e histórias de usuários ao GitPage, vamos elaborá-los em um documento compartilhado no Docs. 
Segue o link abaixo:
https://docs.google.com/document/d/1-_Q0IOZ91PQHBa_3-IegFL8iciRsi7xsV-mE50P4HY0/edit?usp=sharing

**Comment by seraphritt** [comment]
## Conclusão
História dos usuários foram refatoradas e colocadas na gitpage.
## Referências
Link: https://residenciaticbrisa.github.io/T2G2-Chatbot-Participacao-Social/backlog/
