### ISSUE TITLE
Criar Documento de Backlog do Produto

### ISSUE THREAD

**Issue by GZaranza** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#37]
## Descrição
Precisamos criar o documento de backlog do produto para organizar as funcionalidades, histórias de usuário e requisitos elicitados do projeto. O documento será uma referência central para o time de desenvolvimento e stakeholders acompanharem o progresso e as necessidades do produto.

## Tarefas
Liste as tarefas específicas que precisam ser concluídas para resolver o problema ou concluir a tarefa, dívida tarefas grandes e complexas em tarefas simples.
- [x] Criar a estrutura básica do documento de backlog.
- [x] Inserir a tabela de histórias do usuário.
- [x] Adicionar os requisitos elicitados ao documento.
- [x] Revisar e validar o documento com o time de desenvolvimento e stakeholders.

## Testes / Avaliação

- [x] O documento de backlog deve conter uma seção clara e organizada com a tabela de histórias do usuário.
- [x] Os requisitos elicitados devem estar documentados de forma detalhada e compreensível.
- [x] O documento deve ser revisado e aprovado pelo Product Owner e pelo time de desenvolvimento antes de ser considerado finalizado.

**Comment by GZaranza** [comment]
Crie o documento [backlog.md]( https://github.com/ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social/blob/main/docs/backlog.md) com a tabelas das historias de usuario e dos requisitos, precisamos agora preencher.

**Comment by seraphritt** [comment]
## Conclusão
Documento de backlog do produto finalizado e esperando validação do cliente.

## Referências
Link: https://residenciaticbrisa.github.io/T2G2-Chatbot-Participacao-Social/backlog/
