### ISSUE TITLE
Implementação de Storymap para Visualização de Fluxo de Trabalho

### ISSUE THREAD

**Issue by ThiagoMarquesAeroespacial** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#39]
## Descrição
Estamos buscando implementar um Storymap como uma ferramenta de visualização para acompanhar o fluxo de trabalho do nosso projeto. O Storymap é uma técnica eficaz para representar histórias de usuário em relação ao seu posicionamento no tempo e no contexto do desenvolvimento do produto.

## Tarefas

- [x] Pesquisa e Seleção de Ferramenta
- [x] Identificação de Histórias de Usuário
- [x] Criação do Storymap Inicial
- [x] Iteração e Ajustes
- [x] Integração com o Fluxo de Trabalho

## Testes / Avaliação

- [x] A ferramenta selecionada para criar o Storymap está integrada ao nosso ambiente de trabalho e é acessível a todos os membros da equipe.
- [x] O Storymap inicial foi revisado e aprovado pela equipe.

## Responsáveis
Thiago Marques e Gabriel Pinto

## Prazos
08/04/2024

**Comment by Gxaite** [comment]
Roadmap finalizado e apresentado para o grupo, segue o link do Canva https://www.canva.com/design/DAGAEe9BNYs/omkuor2sNPUKJsq6tBSF7A/edit
