### ISSUE TITLE
Definição de uma licença para o chatbot.

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#47]
## Descrição
Nosso bot é um projeto e produto de código aberto, o que significa que estamos comprometidos com a transparência e a colaboração. Nesse sentido, é crucial selecionar a licença mais apropriada para a sua implementação na página do GitHub

## Tarefas
- [x] Pesquisar alternativas de licença
- [x] Apresentar as licenças mais adequadas para o grupo

## Testes / Avaliação
- [x] Validar com o gestor e com o Brisa se a licença escolhida condiz com o projeto

## Prazos
Sprint 4

**Comment by seraphritt** [comment]
# *Conclusão*
Fora utilizada a mesma licença do repositório do Brasil Participativo que pode ser acessada no link da seção de referências.
# *Referências*
https://gitlab.com/lappis-unb/decidimbr/decidim-govbr
