### ISSUE TITLE
Criação de apresentação no canva

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#48]
## Descrição
A elaboração de uma apresentação utilizando o Canva para destacar todo o progresso alcançado pelo grupo ao longo dos últimos dois meses.

## Tarefas
Checklist de slides importantes para a composição da apresentação
- [x] Storymap
- [x] Roadmap BRISA
- [x] Roadmap Cliente
- [x] Gitpage
- [x] Atas de reunião
- [x] Tecnologias
- [x] Histórias de usuário
- [x] Requisitos

## Testes / Avaliação
- [x] Validação da apresentação com o gestor antes da apresentação em grupo.

## Prazos
Antes do dia 04/04/2024

**Comment by Gxaite** [comment]
Link para edição da apresentação no Canva:
https://www.canva.com/design/DAGA0AuvW3Q/_g1f2_4E2RY-ChfJl1GyUA/edit

**Comment by seraphritt** [comment]
Link para visualização do canva:
https://www.canva.com/design/DAGA0AuvW3Q/4jAISOjrbYrtyBlvJCwWug/view?utm_content=DAGA0AuvW3Q&utm_campaign=designshare&utm_medium=link&utm_source=editor
