### ISSUE TITLE
Criação de modelo padrão de commit

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#50]
## Descrição
Implementação de um padrão de commits para uniformizar as contribuições, simplificar a compreensão tanto para o gestor quanto para futuros colaboradores.

## Tarefas
- [x] Procurar modelos de commit.
- [x] Criação do template

## Testes / Avaliação
- [x] Validar com os integrantes se o padrão estabelecido é útil e descritivo.

**Comment by Eruel6** [comment]
O padrão elaborado pode ser visto [aqui](https://github.com/ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social/blob/main/docs/pol%C3%ADticaDeComits.md)
