### ISSUE TITLE
Criação de modelo para PR

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#51]
## Descrição
 É fundamental desenvolver um modelo de padronização para os Pull Requests no GitHub. Afim de auxiliar e padronizar as contribuições ao projeto

## Tarefas
- [x] Procurar modelos para a padronização do PR
- [x] Escolher o melhor método em conjunto 

## Testes / Avaliação
- [x] Validar com o cliente

**Comment by Eruel6** [comment]
O modelo de PR está feito e funcionando de acordo com os pontos que são considerados importantes e foram estabelecidos pelo grupo para um entendimento facilitado e aprovação mais rápida do pull request.
