### ISSUE TITLE
Criação da página de tecnolgias na gitpage

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#52]
## Descrição
Para fornecer uma visão abrangente dos principais recursos empregados na criação do chatbot, é essencial criar uma seção dedicada às tecnologias na página do GitHub.

## Tarefas
- [x] Listar todas as tecnologias usadas
- [x] Descrição das tecnologias

## Testes / Avaliação
- [x] Aprovação dos membros

**Comment by seraphritt** [comment]
# *Conclusão*
Nova página da gitpage criada com as tecnologias utilizadas na primeira release, bem como a definição das mesmas.
A página pode ser acessada pelo link abaixo:
# *Referências*
https://residenciaticbrisa.github.io/T2G2-Chatbot-Participacao-Social/tecnologias/
