### ISSUE TITLE
Criação de uma página para setup de ambiente

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#53]
## Descrição
Para garantir a uniformidade do ambiente de desenvolvimento e facilitar a execução dos scripts e testes do bot, é necessário criar uma página de configuração e um tutorial abrangente.

## Tarefas
- [x] Criar um passo a passo do setup do ambiente
- [x] Revisar o guia para verificar sua eficácia

**Comment by seraphritt** [comment]
## Conclusão
O passo a passo da instalação / configuração do ambiente foi adicionado na página que pode ser acessado pelo link abaixo:

## Referências
Links relacionados:
https://github.com/ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social/tree/telebot_integration
