### ISSUE TITLE
Elaboração de ata de reunião 5

### ISSUE THREAD

**Issue by GabrielSPinto** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#54]
## Descrição
Elaboração de ata de reunião 5

## Tarefas
- [x] Documentação da reunião
- [x] Subir vídeo no YT

## Testes / Avaliação
- [x] Validação com outros membros

## Responsáveis
Gabriel
Thiago Marques

## Prazos
01/04/2024

**Comment by ThiagoMarquesAeroespacial** [comment]
link da ata reunião 5:
https://residenciaticbrisa.github.io/T2G2-Chatbot-Participacao-Social/atas_de_reuni%C3%B5es/Reuni%C3%A3o%205/
