### ISSUE TITLE
Criar um cronograma geral

### ISSUE THREAD

**Issue by ThiagoMarquesAeroespacial** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#56]
## Descrição
O objetivo desta issue é criar um cronograma geral do projeto para garantir uma gestão eficaz do tempo e dos recursos. O cronograma ajudará a manter o projeto dentro do prazo e a identificar eventuais gargalos ou atrasos que possam surgir ao longo do caminho.

## Tarefas
- [x] Identificar todas as etapas principais do projeto.
- [x] Descrever as entregas das Releases.

## Testes / Avaliação
- [x] O cronograma permite uma gestão eficaz do tempo e dos recursos ao longo do projeto?

## Responsáveis
- @Gxaite 

## Prazos
- 04/04/2024

**Comment by Gxaite** [comment]
O cronograma que tinhamos anteriormente foi dividido em dois, um mais detalhado com datas aproximadas de cada entrega e outro mais geral para uma consulta rápida do cronograma que iremos seguir no projeto Brisa. Segue o link do cronograma geral tps://residenciaticbrisa.github.io/T2G2-Chatbot-Participacao-Social/cronogramas/Cronograma%20Geral/
