### ISSUE TITLE
Integração entre Rocket.Chat e Rasa

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#66]
## Descrição
Necessitamos integrar o Rocket.Chat, nossa plataforma de comunicação, com o Rasa, um framework de inteligência artificial para conversação. O objetivo é automatizar respostas no nosso serviço de atendimento ao cliente.

## Tarefas
- [ ] Estudar a API do Rocket.Chat e documentar os pontos de integração possíveis com o Rasa.
- [ ] Desenvolver um protótipo de conexão entre as plataformas utilizando uma instância de teste do Rocket.Chat.
- [ ] Configurar o webhook no Rasa para receber mensagens do Rocket.Chat.
- [ ] Criar documentação para a integração, focando em facilitar futuras manutenções e expansões.

## Testes / Avaliação
- [ ] Verificar se o bot responde corretamente a uma variedade de perguntas frequentes de usuários no ambiente de teste do Rocket.Chat.
- [ ] Avaliar a estabilidade da conexão entre o Rasa e o Rocket.Chat em diferentes condições de rede.

**Comment by Gxaite** [comment]
Estamos enfrentando dificuldades com essa integração atualmente. Apesar de termos buscado suporte junto à comunidade, ainda não recebemos retorno nem da equipe do Rocket.Chat nem do Rasa. Continuamos nossos esforços e estudos para resolver esse problema.

**Comment by Eruel6** [comment]
Durante as pesquisas no fórum do RASA chegamos nesta parte onde podemos verificar que pode ser aumentado o número de workers dentro do da API, o que poderia ser uma saída de como manter várias conversas em andamnto.
[link para o fórum](https://rasa.com/docs/rasa/http-api/)

**Comment by seraphritt** [comment]
Como optamos por não utilizar mais o Rasa, essa issue será fechada.
