### ISSUE TITLE
Elaboração de ata da reunião 7

### ISSUE THREAD

**Issue by GabrielSPinto** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#67]
## Descrição:
Elaboração de ata da reunião 7.

## Tarefas:
- [x] Acompanhamento da reunião;
- [x] Elaboração de doc da Reunião;
- [x] Conversão em mkdocs;
- [x] Commit da ata;

## Testes / Avaliação:
- [x] Validação com outros membros.

## Responsáveis:
Gabriel Santos Pinto
Thiago Henrique Marques Rocha

## Prazo:
15/04/2024

**Comment by ThiagoMarquesAeroespacial** [comment]
Ata criada e localizada no link:

https://residenciaticbrisa.github.io/T2G2-Chatbot-Participacao-Social/atas_de_reuni%C3%B5es/Reuni%C3%A3o%207/
