### ISSUE TITLE
Elaboração de ata da reunião 08

### ISSUE THREAD

**Issue by ThiagoMarquesAeroespacial** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#72]
## Descrição
Elaboração de ata da reunião 8.

## Tarefas

- [x] Acompanhamento da reunião;
- [x] Elaboração de doc da Reunião;
- [x]  Conversão em mkdocs;
- [x]  Commit da ata;

## Testes / Avaliação

- [ ] Validação com outros membros.

**Comment by GabrielSPinto** [comment]
Criado e revisado:
[LINK](https://residenciaticbrisa.github.io/T2G2-Chatbot-Participacao-Social/atas_de_reuni%C3%B5es/Reuni%C3%A3o%208/)
