### ISSUE TITLE
Migração do banco de dados do Botpress

### ISSUE THREAD

**Issue by Eruel6** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#73]
## Descrição
Por padrão o botpress vem configurando com um banco SQLite, mas é altamente recomendável a troca po um banco de dados mais robusto, o botpress possui suporte a um banco de dados postgresql, então foi decidido pela equipe a migração para o banco postgres, para uma maior segurança à falhas e robustez uma vez que o bot desenvolvido deve ser robusto. 

## Tarefas
- [x] Estudar formas de migração do banco.
- [x] Realizar a migração do banco localmente.
- [x] Realizar a migração do banco no ambiente remoto.

## Testes / Avaliação 
- [x] Banco de dados funcionando de forma esperada no ambiente remoto.

**Comment by Eruel6** [comment]
A migração do banco está funcinando localmente, com isso precisamos fazer a migração no ambiente virtual agora. O banco pode ser conferido na imagem abaixo, com todas as tabelas nescessárias para o funcionamento do botpress criadas.

![image](https://github.com/ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social/assets/71983159/fdbc9238-2edd-4ea3-be05-c4c62409b808)

**Comment by Gxaite** [comment]
O banco de dados foi devidamente migrado e está atualmente em funcionamento para a maioria dos membros. No entanto, ainda existem alguns problemas a serem resolvidos. Iremos abrir uma issue para investigar e abordar esses problemas de implementação de forma mais detalhada.
