### ISSUE TITLE
Configuração do Docker para o servidor botpressv12.26.7

### ISSUE THREAD

**Issue by GZaranza** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#74]
## Descrição
Precisamos configurar um ambiente Docker para o servidor botpressev12.26.7. O Docker deve ser configurado para puxar automaticamente os arquivos necessários do repositório do projeto.

## Tarefas
Liste as tarefas específicas que precisam ser concluídas para resolver o problema ou concluir a tarefa, dívida tarefas grandes e complexas em tarefas simples.
- [x] Criar o Dockerfile baseado na versão mais recente de uma imagem oficial
- [x] Adicionar comandos no Dockerfile para instalar dependências específicas do projeto.
- [x] Configurar scripts no Dockerfile para clonar o repositório do projeto ou puxar atualizações antes do lançamento do servidor.
- [x] Escrever documentação sobre como construir e executar a imagem Docker.

## Testes / Avaliação
Uma configuração de Docker completamente funcional que permita aos desenvolvedores e à infraestrutura de produção executar e atualizar o servidor botpressev12.26.7 de forma eficiente e confiável.

**Comment by Gxaite** [comment]
O Docker Compose foi devidamente criado e configurado. Agora, partiremos para o detalhamento da documentação e organização do ambiente para rodar o servidor.
