### ISSUE TITLE
Melhorar a Linguagem Natural e o Fluxo de Resposta do Bot

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#78]
### Contexto:
O bot atualmente usa uma linguagem natural que pode ser melhorada para aumentar a compreensão dos usuários e tornar as interações mais eficientes.

### Problema:
- A linguagem natural do bot é às vezes confusa ou pouco clara.
- O fluxo de resposta pode ser otimizado para fornecer informações de maneira mais eficiente e coerente.

### Tarefas:
- [x] Revisar e refinar a linguagem natural atual do bot.
- [x] Analisar e otimizar o fluxo de resposta do bot.
- [x] Desenvolver uma nova estrutura de resposta mais fluente.

### Testes / Avaliação:
- [x] Verificar a compreensão dos usuários por meio de testes de usabilidade.
- [x] Medir a taxa de conclusão de consultas dos usuários após as alterações.

**Comment by seraphritt** [comment]
# Conclusão
A presidência optou por seguir com o chatbot utilizando botões e não linguagem natural e também forneceu o link para o figma do fluxo que deve ser implementado.
