### ISSUE TITLE
Configuração do ambiente Python

### ISSUE THREAD

**Issue by seraphritt** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#8]
## Descrição
Utilizar prefencialmente o venv para criar um ambiente virtual utlizando a versão 3.10 do Python.

## Tarefas
   - [ ] Configurar o venv utilizando o comando ``python3 -m venv <nome_do_venv>``
   - [ ] Atualizar o pip, com o comando ``pip install --upgrade pip``
  
## Testes / Avaliação
- [ ] Verificar se todos as tarefas foram feitas com sucesso

**Comment by GabrielSPinto** [comment]
Pra rodar o ambiente virtual é necessário o comando `source .venv/bin/activate` e para sair do venv comando `deactivate`
