### ISSUE TITLE
Implementação de teste de usabilidade do bot

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#82]
## Descrição
Precisamos criar um teste de usabilidade para o chatbot implementado no projeto. O objetivo é avaliar a eficácia, eficiência e satisfação dos usuários ao interagir com o chatbot. Este teste nos ajudará a identificar pontos fortes e áreas de melhoria na experiência do usuário.

## Tarefas
Liste as tarefas específicas que precisam ser concluídas para resolver o problema ou concluir a tarefa. Divida tarefas grandes e complexas em tarefas simples.
- [x] Definir os objetivos do teste de usabilidade
- [x] Elaborar um plano de teste de usabilidade
- [x] Selecionar participantes representativos do público-alvo
- [x] Preparar o ambiente e as ferramentas necessárias para o teste
- [x] Conduzir sessões de teste de usabilidade com os participantes
- [x] Coletar e analisar os dados das sessões de teste
- [x] Documentar os resultados e principais descobertas
- [x] Propor melhorias com base nos resultados do teste
- [x] Implementar as melhorias identificadas

**Comment by Gxaite** [comment]
Segue abaixo link para o TCC da monitora do BRISA, Bruna pinos, seu tcc foi baseado no estudo e criação de um chatbot. O estudo do documento será de grande valor para o desenvolvimento do bot
https://bdm.unb.br/handle/10483/29911

**Comment by seraphritt** [comment]
O chatbot está presente no servidor de homologação e está sendo testado.
