### ISSUE TITLE
Estudo de Personalidade do Bot e Criação de uma Persona

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#90]
## Descrição
Precisamos realizar um estudo para definir a personalidade do nosso bot e criar uma persona que guiará suas interações com os usuários. Esse processo ajudará a garantir que o bot tenha uma identidade clara e consistente, melhorando a experiência do usuário.

## Tarefas
Liste as tarefas específicas que precisam ser concluídas para resolver o problema ou concluir a tarefa. Divida tarefas grandes e complexas em tarefas simples.
- [x] Pesquisar e definir os atributos de personalidade desejados para o bot
- [x] Analisar o público-alvo e suas expectativas em relação ao bot
- [x] Coletar exemplos de bots existentes com personalidades bem-definidas
- [x] Realizar brainstorm com a equipe para discutir ideias e características
- [x] Elaborar um perfil detalhado da persona do bot, incluindo nome, idade, interesses, tom de voz e estilo de comunicação
- [x] Criar exemplos de diálogos e respostas que reflitam a personalidade do bot
- [x] Validar a persona com a equipe e ajustar conforme necessário
- [x] Documentar a persona e os atributos de personalidade para futuras referências

**Comment by seraphritt** [comment]
Uma vez que o chatbot usará apenas botões, não será necessário uma persona.
