### ISSUE TITLE
Alteração da Identidade Visual e Balões de Mensagens

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#91]
## Descrição
Precisamos atualizar a identidade visual do nosso chatbot, incluindo a personalização dos balões de mensagens. Esta alteração visa melhorar a estética e a usabilidade da interface do chatbot, tornando-a mais atraente e alinhada com a marca do projeto.

## Tarefas
- [x] Analisar a identidade visual atual e identificar áreas de melhoria
- [x] Pesquisar referências de design com base nas inforações passadas pela presidência
- [x] Criar protótipos dos novos balões de mensagens e elementos visuais
- [x] Revisar e obter feedback da equipe sobre os protótipos
- [x] Implementar as mudanças na identidade visual e nos balões de mensagens no chatbot
- [x] Testar a nova identidade visual em diferentes dispositivos e resoluções
- [x] Documentar as alterações e atualizar os guias de estilo do projeto

**Comment by seraphritt** [comment]
Serão necessários testes para responsividade em dispositivos móveis, tablets e computadores.
Nos computadores o chat não deve cobrir toda a tela, mas nos dispositivos móveis sim.
